### ISSUE TITLE
New Feature ✨: Enable Request Term

### ISSUE THREAD

**Issue by adrian-wego** [wego-technologies/freightwebster#8]
Description:
- Activate the term submission feature to capture user-requested terms.
- Store submitted terms in the database and display them under a new "Requested" tab.
- Sort the list of requested terms by the date.
- Prevent the display of these terms in the main tabs; they should only appear in the "Requested" tab.
- If the term in the database has no definition, automatically categorize it as "requested" over using the current "visible" true/false field.

**Comment by denisqdenisq** [comment]
bonus item: create upvote system

**Comment by Dorcy64** [comment]
Working on the endpoint for this rq
